Algoritmo "String"

Var
v:vetor [0..1] de caracter
indice, ecidni: inteiro

Inicio

escreva("Informe uma palavra: ")
leia(v[indice])

para indice de 0 ate 1 faca
     se v[0] = ("") entao
     escreva(" ")
     senao
     escreva(v[0])
     fimse
fimpara

para ecidni de 1 ate 0 faca
     se v[0] = ("") entao
     escreva(" ")
     senao
     escreva(v[0])
     fimse
fimpara

Fimalgoritmo